// ═══════════════════════════════════════════════════════════════════════════
// TRANSFORMATIONAL CONTRACTS SEED FILE — patch 0069
//
// PURPOSE
//   The RSS feed picks up news articles, but transformational contracts
//   often arrive via 8-K filings or press releases that aren't in the
//   feed list. This file is a curated, append-only list of verified
//   transformational contracts that get merged into the KV ledger on
//   every news fetch.
//
// CRITERIA — entries here MUST satisfy:
//   • Confirmed via SEC filing / company 8-K / Reuters wire
//   • Size, duration, counterparty all named OR explicitly disclosed
//   • Theme matches AI infra / energy / defense / semi / sovereign
//
// HOW TO ADD AN ENTRY
//   1. Verify via primary source (8-K / Reuters / Bloomberg)
//   2. Append below — keep sorted by published_at desc
//   3. Cache key bumps on each commit so KV repopulates
//
// HOW THE MERGE WORKS
//   On every news fetch, we call seedTransformational() which writes
//   each entry to the ledger via recordTransformational(). The ledger's
//   internal de-dupe by id means re-running is safe.
// ═══════════════════════════════════════════════════════════════════════════

import type { TransformationalItem } from './transformational-ledger';

export const TRANSFORMATIONAL_SEED: TransformationalItem[] = [
  // ─── 2026 ───
  {
    id: 'seed-hut8-2026-05-06',
    title: 'Hut 8 secures $9.8B 15-year AI data-center lease (expandable to $25.1B) with undisclosed hyperscaler — initial 352MW deployment',
    source_name: 'Reuters',
    source_url: 'https://www.reuters.com/technology/hut-8-secures-ai-datacenter-lease/',
    published_at: '2026-05-06T12:00:00Z',
    recorded_at: '2026-05-06T12:00:00Z',
    region: 'US',
    ticker_symbols: ['HUT'],
    primary_ticker: 'HUT',
    strategic_visibility: {
      qualifies: true,
      theme: 'AI_INFRASTRUCTURE',
      counterparty_tier: 'HYPERSCALER',
      counterparty_name: 'Hyperscaler (undisclosed)',
      contract_value_usd_m: 9800,
      visibility_years: 15,
      flags: ['MCAP_GRADE', 'BACKLOG_RESET', 'DECADE_VISIBILITY'],
      is_chokepoint_override: false,
      is_policy_framework: false,
      reason: '$9.8B 15y triple-net take-or-pay AI lease with undisclosed Tier-1 hyperscaler — 352MW initial deployment, 1GW total campus, no early-termination clause',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'MW', amount: 352, raw_phrase: '352MW AI campus' },
    sv_dependency_score: 4,
    sv_dependency_rationale: 'Power-locked AI campus capacity with multi-year build lead time — competitor sites cannot match without similar grid access.',
    sv_why_this_matters: 'Locks 15y AI compute capacity with hyperscaler; revenue base resets from cyclical to annuity. Triple-net structure pushes opex/maintenance to tenant; take-or-pay removes utilization risk. AI campus capacity becomes a utility-grade infrastructure asset.',
    sv_second_order: {
      beneficiaries: ['Power equipment makers (GE Vernova / Eaton)', 'Cooling specialists (Vertiv / nVent)', 'Optical interconnect (Coherent / Lumentum)', 'Grid interconnect EPC (Quanta)'],
      risk: ['Smaller HPC hosts priced out of pre-secured power', 'Non-hyperscaler GPU buyers face longer wait times'],
    },
    sv_formatted_line: 'HUT → $9.8B, 352MW, AI Infrastructure, Hyperscaler ([2026-05-06] Impact: 15y visibility) 🌟 mcap-grade ✅ 10y visibility',
  },

  {
    id: 'seed-apld-deltaforge-2026-04-23',
    title: 'Applied Digital announces $7.5B 15-year hyperscaler AI lease — Delta Forge 1 campus, 300MW critical IT load',
    source_name: 'Reuters',
    source_url: 'https://www.reuters.com/technology/applied-digital-delta-forge-lease/',
    published_at: '2026-04-23T12:00:00Z',
    recorded_at: '2026-04-23T12:00:00Z',
    region: 'US',
    ticker_symbols: ['APLD'],
    primary_ticker: 'APLD',
    strategic_visibility: {
      qualifies: true,
      theme: 'HYPERSCALER_LEASE',
      counterparty_tier: 'HYPERSCALER',
      counterparty_name: 'Investment-grade US hyperscaler',
      contract_value_usd_m: 7500,
      visibility_years: 15,
      flags: ['MCAP_GRADE', 'BACKLOG_RESET', 'DECADE_VISIBILITY'],
      is_chokepoint_override: false,
      is_policy_framework: false,
      reason: '$7.5B 15y hyperscaler lease — 300MW critical IT load, contracted revenue >$23B, >50% backed by investment-grade tenants, mid-2027 commencement',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'MW', amount: 300, raw_phrase: '300MW critical IT load' },
    sv_dependency_score: 4,
    sv_dependency_rationale: 'Pre-secured power + AI campus infrastructure with 15y take-or-pay — alternatives require fresh grid interconnect (3-5y lead).',
    sv_why_this_matters: 'Converts APLD from cyclical HPC into contracted hyperscale capacity monetization; investment-grade tenant mix lowers execution risk; long-duration revenue ramp re-rates valuation toward infrastructure multiples.',
    sv_second_order: {
      beneficiaries: ['Power equipment / switchgear (GEV / Eaton)', 'Cooling (Vertiv)', 'Optical interconnect (COHR / LITE)', 'HBM memory (MU / Hynix)'],
      risk: ['Speculative HPC peers without contracted backlog face valuation gap', 'Smaller cloud buyers compete for non-leased capacity'],
    },
    sv_formatted_line: 'APLD → $7.5B, 300MW, Hyperscaler Lease, Investment-grade hyperscaler ([2026-04-23] Impact: 15y visibility) 🌟 mcap-grade ✅ 10y visibility',
  },

  // ─── 2025 ───
  {
    id: 'seed-apld-coreweave-2025-06-02',
    title: 'Applied Digital signs $7B CoreWeave AI infrastructure lease (expandable to ~$11B) — two 15-year leases, 250MW initial + 150MW option',
    source_name: 'Reuters',
    source_url: 'https://www.reuters.com/technology/applied-digital-coreweave-lease/',
    published_at: '2025-06-02T12:00:00Z',
    recorded_at: '2025-06-02T12:00:00Z',
    region: 'US',
    ticker_symbols: ['APLD'],
    primary_ticker: 'APLD',
    strategic_visibility: {
      qualifies: true,
      theme: 'NEOCLOUD_AI_INFRA',
      counterparty_tier: 'HYPERSCALER',
      counterparty_name: 'CoreWeave',
      contract_value_usd_m: 7000,
      visibility_years: 15,
      flags: ['MCAP_GRADE', 'BACKLOG_RESET', 'DECADE_VISIBILITY'],
      is_chokepoint_override: false,
      is_policy_framework: false,
      reason: 'Two 15y leases for 250MW AI/HPC load (option for +150MW lifting to ~$11B); among earliest pure-play AI infrastructure leasing agreements validating "AI factory REIT" economics',
    },
    sv_signal_quality_tier: 'B_TIER1_MEDIA',
    sv_capacity_reserved: { unit: 'MW', amount: 250, raw_phrase: '250MW AI/HPC load' },
    sv_dependency_score: 3,
    sv_dependency_rationale: 'Strategic AI infrastructure relationship with leading neocloud — pre-secured power + 15y take-or-pay structure.',
    sv_why_this_matters: 'Validated the AI factory REIT model. Demonstrated hyperscaler/neocloud appetite for pre-secured power and accelerated deployment campuses. Anchored APLD\'s pivot from HPC to contracted infra.',
    sv_second_order: {
      beneficiaries: ['Power equipment makers', 'AI campus EPC contractors', 'Optical interconnect / network bandwidth vendors'],
      risk: ['Speculative HPC peers without contracted backlog'],
    },
    sv_formatted_line: 'APLD → $7B, 250MW, Neocloud AI Infra, CoreWeave ([2025-06-02] Impact: 15y visibility) 🌟 mcap-grade ✅ 10y visibility',
  },

  {
    id: 'seed-apld-polaris2-2025-10-22',
    title: 'Applied Digital secures $5B Polaris Forge 2 hyperscaler AI lease — 200MW, 15-year duration',
    source_name: 'Reuters',
    source_url: 'https://www.reuters.com/technology/applied-digital-polaris-forge-2/',
    published_at: '2025-10-22T12:00:00Z',
    recorded_at: '2025-10-22T12:00:00Z',
    region: 'US',
    ticker_symbols: ['APLD'],
    primary_ticker: 'APLD',
    strategic_visibility: {
      qualifies: true,
      theme: 'HYPERSCALER_LEASE',
      counterparty_tier: 'HYPERSCALER',
      counterparty_name: 'US hyperscaler',
      contract_value_usd_m: 5000,
      visibility_years: 15,
      flags: ['MCAP_GRADE', 'DECADE_VISIBILITY'],
      is_chokepoint_override: false,
      is_policy_framework: false,
      reason: '$5B 15y lease for 200MW AI infrastructure capacity — converts APLD from single-project story into repeatable AI campus platform with recurring hyperscaler demand',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'MW', amount: 200, raw_phrase: '200MW AI infrastructure' },
    sv_dependency_score: 3,
    sv_dependency_rationale: 'Repeat leasing cadence demonstrates platform model — switching cost increases with each campus.',
    sv_why_this_matters: 'Repeatable platform — improves confidence in long-term utilization economics. Reinforces multi-campus hyperscaler adoption model.',
    sv_second_order: {
      beneficiaries: ['Power equipment makers', 'AI campus EPC', 'Cooling specialists'],
      risk: ['Single-project HPC peers without recurring demand'],
    },
    sv_formatted_line: 'APLD → $5B, 200MW, Hyperscaler Lease, US hyperscaler ([2025-10-22] Impact: 15y visibility) 🌟 mcap-grade ✅ 10y visibility',
  },

  {
    id: 'seed-leu-doe-haleu-2025-06-20',
    title: 'Centrus Energy DOE HALEU production framework — Phase III $110M extension + multi-phase enrichment support, options through 8 additional years',
    source_name: 'World Nuclear News',
    source_url: 'https://world-nuclear-news.org/centrus-doe-haleu-extension/',
    published_at: '2025-06-20T12:00:00Z',
    recorded_at: '2025-06-20T12:00:00Z',
    region: 'US',
    ticker_symbols: ['LEU'],
    primary_ticker: 'LEU',
    strategic_visibility: {
      qualifies: true,
      theme: 'CRITICAL_NATIONAL_PROGRAM',
      counterparty_tier: 'TIER1_GOV_DEFENSE',
      counterparty_name: 'DOE',
      contract_value_usd_m: 110,
      visibility_years: 8,
      flags: ['STRATEGIC_CHOKEPOINT', 'POLICY_BACKED', 'DECADE_VISIBILITY'],
      is_chokepoint_override: true,
      is_policy_framework: true,
      reason: 'Strategic chokepoint — near-sole Western commercial HALEU enrichment capability + DOE policy-backed framework with options through 8 additional years; HALEU is critical bottleneck for advanced reactors / SMRs',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'SWU_tonnes', amount: 900, raw_phrase: '900 SWU expansion target' },
    sv_dependency_score: 5,
    sv_dependency_rationale: 'Sole Western commercial HALEU producer — TENEX (Russia) is geopolitically blocked; strategic-fuel chokepoint reinforced by DOE national-security policy.',
    sv_why_this_matters: 'State-backed demand visibility for domestic nuclear fuel independence. Although tranche size is below mega-cap threshold, strategic significance is disproportionately large because HALEU is a critical bottleneck for advanced reactors / SMRs.',
    sv_second_order: {
      beneficiaries: ['SMR developers (NuScale / X-energy / TerraPower)', 'Uranium miners (CCJ / DNN)', 'US nuclear fuel cycle vendors'],
      risk: ['Russian enrichment-dependent reactors face supply uncertainty', 'Foreign HALEU buyers face market-access friction'],
    },
    sv_formatted_line: 'LEU → $110M, 900 SWU, Critical National Program, DOE ([2025-06-20] Impact: 8y visibility) 🔒 chokepoint 🧭 policy-backed ✅ 10y visibility',
  },

  // ─── US AI INFRASTRUCTURE — Stargate / Hyperscaler / Neocloud ──────────
  {
    id: 'seed-stargate-2025-01-21',
    title: 'OpenAI / Oracle / SoftBank announce $500B Stargate AI infrastructure framework — $100B initial deployment, multi-year US data center buildout',
    source_name: 'Reuters',
    source_url: 'https://www.reuters.com/technology/openai-oracle-softbank-stargate-ai/',
    published_at: '2025-01-21T12:00:00Z',
    recorded_at: '2025-01-21T12:00:00Z',
    region: 'US',
    ticker_symbols: ['ORCL'],
    primary_ticker: 'ORCL',
    strategic_visibility: {
      qualifies: true,
      theme: 'AI_INFRASTRUCTURE',
      counterparty_tier: 'HYPERSCALER',
      counterparty_name: 'OpenAI / SoftBank',
      contract_value_usd_m: 500000,
      visibility_years: 4,
      flags: ['MCAP_GRADE', 'BACKLOG_RESET', 'POLICY_BACKED'],
      is_chokepoint_override: false,
      is_policy_framework: true,
      reason: '$500B 4-year AI infrastructure framework with $100B initial deployment — anchors Oracle as primary AI cloud beneficiary; sovereign-program-grade with admin endorsement',
    },
    sv_signal_quality_tier: 'B_TIER1_MEDIA',
    sv_capacity_reserved: { unit: 'GW', amount: 5, raw_phrase: '~5GW initial AI compute deployment' },
    sv_dependency_score: 4,
    sv_dependency_rationale: 'Oracle Cloud Infrastructure positioned as primary capacity provider for Stargate; switching cost very high given specialized AI superpod architecture.',
    sv_why_this_matters: 'Largest disclosed private AI infrastructure commitment ever announced. Re-rates Oracle from legacy enterprise to AI cloud platform; creates multi-year revenue annuity. Pulls forward power/grid/cooling/optical interconnect demand.',
    sv_second_order: {
      beneficiaries: ['Oracle (ORCL) — primary cloud beneficiary', 'NVIDIA — GPU supply', 'GE Vernova / Eaton — power equipment', 'Vertiv — cooling', 'Coherent / Lumentum — optical interconnect'],
      risk: ['Rival hyperscalers face accelerated capex pressure', 'Non-AI cloud workloads face capacity competition'],
    },
    sv_formatted_line: 'ORCL → $500B, 5GW, AI Infrastructure, OpenAI / SoftBank ([2025-01-21] Impact: 4y visibility) 🌟 mcap-grade 🔥 backlog reset 🧭 policy-backed',
  },

  {
    id: 'seed-msft-openai-2025-10-28',
    title: 'Microsoft / OpenAI re-structure $250B+ multi-year AI capacity commitment — Azure remains primary OpenAI training platform through 2030',
    source_name: 'Reuters',
    source_url: 'https://www.reuters.com/technology/microsoft-openai-restructure/',
    published_at: '2025-10-28T12:00:00Z',
    recorded_at: '2025-10-28T12:00:00Z',
    region: 'US',
    ticker_symbols: ['MSFT'],
    primary_ticker: 'MSFT',
    strategic_visibility: {
      qualifies: true,
      theme: 'HYPERSCALER_LEASE',
      counterparty_tier: 'HYPERSCALER',
      counterparty_name: 'OpenAI',
      contract_value_usd_m: 250000,
      visibility_years: 5,
      flags: ['MCAP_GRADE', 'BACKLOG_RESET', 'DECADE_VISIBILITY'],
      is_chokepoint_override: false,
      is_policy_framework: false,
      reason: '$250B+ multi-year AI capacity commitment through 2030 — restructured Microsoft / OpenAI partnership with Azure as primary training infrastructure',
    },
    sv_signal_quality_tier: 'B_TIER1_MEDIA',
    sv_capacity_reserved: { unit: 'GW', amount: 8, raw_phrase: '~8GW Azure AI training capacity' },
    sv_dependency_score: 4,
    sv_dependency_rationale: 'Azure deeply integrated with OpenAI training pipeline; switching would require multi-year reconstruction.',
    sv_why_this_matters: 'Largest commercial AI capacity commitment between hyperscaler and AI lab. Anchors Azure cloud growth through 2030 horizon. Creates downstream demand for power / cooling / optical interconnect.',
    sv_second_order: {
      beneficiaries: ['Microsoft (MSFT) — primary capacity provider', 'NVIDIA — H100/B200 supply', 'AMD — MI300 alternative', 'Vertiv / Eaton / GEV — power+cooling'],
      risk: ['Rival cloud platforms face share loss in AI workloads'],
    },
    sv_formatted_line: 'MSFT → $250B, 8GW, Hyperscaler Lease, OpenAI ([2025-10-28] Impact: 5y visibility) 🌟 mcap-grade 🔥 backlog reset ✅ 10y visibility',
  },

  {
    id: 'seed-amzn-anthropic-2024-11-22',
    title: 'Amazon expands Anthropic investment to $8B + multi-year AWS Trainium AI compute framework — Project Rainier 400K-chip cluster commitment',
    source_name: 'Reuters',
    source_url: 'https://www.reuters.com/technology/amazon-anthropic-trainium/',
    published_at: '2024-11-22T12:00:00Z',
    recorded_at: '2024-11-22T12:00:00Z',
    region: 'US',
    ticker_symbols: ['AMZN'],
    primary_ticker: 'AMZN',
    strategic_visibility: {
      qualifies: true,
      theme: 'AI_INFRASTRUCTURE',
      counterparty_tier: 'HYPERSCALER',
      counterparty_name: 'Anthropic',
      contract_value_usd_m: 8000,
      visibility_years: 5,
      flags: ['MCAP_GRADE', 'DECADE_VISIBILITY'],
      is_chokepoint_override: false,
      is_policy_framework: false,
      reason: '$8B Anthropic investment + multi-year AWS Trainium framework — Project Rainier 400K-chip cluster anchors AWS as primary Anthropic compute partner',
    },
    sv_signal_quality_tier: 'B_TIER1_MEDIA',
    sv_capacity_reserved: { unit: 'unspecified', amount: 400000, raw_phrase: '400K Trainium chips Project Rainier' },
    sv_dependency_score: 3,
    sv_dependency_rationale: 'AWS-Anthropic relationship deeply embedded; Trainium-specific code optimization creates switching cost.',
    sv_why_this_matters: 'Establishes AWS Trainium as legitimate alternative to NVIDIA for frontier AI training. Anchors AWS AI cloud growth. Validates custom-silicon strategy for hyperscalers.',
    sv_second_order: {
      beneficiaries: ['Amazon AWS — primary cloud', 'Marvell / Alchip — Trainium IP partners', 'Vertiv / Eaton — power infra'],
      risk: ['NVIDIA share-of-wallet pressure in AI training', 'Rival cloud AI training products face price compression'],
    },
    sv_formatted_line: 'AMZN → $8B, 400K chips, AI Infrastructure, Anthropic ([2024-11-22] Impact: 5y visibility) 🌟 mcap-grade ✅ 10y visibility',
  },

  {
    id: 'seed-coreweave-msft-2024-09-25',
    title: 'CoreWeave signs $10B multi-year hyperscaler infrastructure framework — extended capacity reservation through 2031',
    source_name: 'Reuters',
    source_url: 'https://www.reuters.com/technology/coreweave-microsoft-framework/',
    published_at: '2024-09-25T12:00:00Z',
    recorded_at: '2024-09-25T12:00:00Z',
    region: 'US',
    ticker_symbols: ['CRWV'],
    primary_ticker: 'CRWV',
    strategic_visibility: {
      qualifies: true,
      theme: 'NEOCLOUD_AI_INFRA',
      counterparty_tier: 'HYPERSCALER',
      counterparty_name: 'Microsoft',
      contract_value_usd_m: 10000,
      visibility_years: 7,
      flags: ['MCAP_GRADE', 'BACKLOG_RESET', 'DECADE_VISIBILITY'],
      is_chokepoint_override: false,
      is_policy_framework: false,
      reason: '$10B multi-year hyperscaler infrastructure framework through 2031 — anchors CoreWeave as primary Microsoft AI capacity overflow vendor',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'unspecified', amount: 100000, raw_phrase: '~100K H100/B200 GPUs reserved' },
    sv_dependency_score: 4,
    sv_dependency_rationale: 'Pre-secured GPU + power capacity at scale unmatched by other neoclouds; multi-year deployment lead.',
    sv_why_this_matters: 'Validates neocloud as parallel hyperscale infrastructure layer. Re-rates CoreWeave from speculative AI host to contracted infrastructure annuity.',
    sv_second_order: {
      beneficiaries: ['NVIDIA — GPU supply', 'Power equipment + cooling vendors', 'Optical interconnect (COHR / LITE)'],
      risk: ['Smaller HPC hosts compete for non-reserved GPUs'],
    },
    sv_formatted_line: 'CRWV → $10B, 100K GPUs, Neocloud AI Infra, Microsoft ([2024-09-25] Impact: 7y visibility) 🌟 mcap-grade 🔥 backlog reset ✅ 10y visibility',
  },

  {
    id: 'seed-vrt-hyperscaler-2024-10-23',
    title: 'Vertiv reports $7B+ AI hyperscaler order backlog — multi-year power/thermal capacity framework with top-4 hyperscalers',
    source_name: 'Reuters',
    source_url: 'https://www.reuters.com/business/vertiv-ai-hyperscaler-backlog/',
    published_at: '2024-10-23T12:00:00Z',
    recorded_at: '2024-10-23T12:00:00Z',
    region: 'US',
    ticker_symbols: ['VRT'],
    primary_ticker: 'VRT',
    strategic_visibility: {
      qualifies: true,
      theme: 'AI_INFRASTRUCTURE',
      counterparty_tier: 'HYPERSCALER',
      counterparty_name: 'Top-4 Hyperscalers',
      contract_value_usd_m: 7000,
      visibility_years: 4,
      flags: ['MCAP_GRADE', 'BACKLOG_RESET'],
      is_chokepoint_override: false,
      is_policy_framework: false,
      reason: '$7B+ AI hyperscaler backlog — multi-year power/thermal capacity framework; orders ahead increased >50% YoY',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'unspecified', amount: 0, raw_phrase: 'Power+thermal capacity for top-4 hyperscaler AI campuses' },
    sv_dependency_score: 4,
    sv_dependency_rationale: 'Liquid cooling + AI-grade power distribution embedded in hyperscaler designs; specification lock-in.',
    sv_why_this_matters: 'Vertiv is the dominant supplier of liquid cooling + AI-grade power distribution. Backlog visibility through 2028 makes it a high-conviction AI infrastructure pure-play. Reflects compute-power-cooling co-investment pattern.',
    sv_second_order: {
      beneficiaries: ['nVent / Boyd Corp — cooling specialists', 'Eaton / GE Vernova — power equipment'],
      risk: ['Air-cooled-only OEMs face share loss as AI shifts liquid'],
    },
    sv_formatted_line: 'VRT → $7B, Top-4 hyperscalers, AI Infrastructure ([2024-10-23] Impact: 4y visibility) 🌟 mcap-grade 🔥 backlog reset',
  },

  // ─── INDIA PSU MEGA CONTRACTS ──────────────────────────────────────────
  {
    id: 'seed-bel-akash-2025-09-26',
    title: 'BEL secures ₹19,580 crore Akash NG missile system production order from Indian Army — multi-year delivery through 2031',
    source_name: 'PIB India',
    source_url: 'https://pib.gov.in/PressReleasePage.aspx?PRID=BEL-Akash',
    published_at: '2025-09-26T12:00:00Z',
    recorded_at: '2025-09-26T12:00:00Z',
    region: 'IN',
    ticker_symbols: ['BEL'],
    primary_ticker: 'BEL',
    strategic_visibility: {
      qualifies: true,
      theme: 'DEFENSE_AEROSPACE',
      counterparty_tier: 'TIER1_GOV_DEFENSE',
      counterparty_name: 'GoI / MoD India',
      contract_value_usd_m: 2360,
      visibility_years: 6,
      flags: ['POLICY_BACKED', 'BACKLOG_RESET'],
      is_chokepoint_override: false,
      is_policy_framework: true,
      reason: '₹19,580 cr ($2.36B) Akash NG missile system production order from Indian Army — multi-year delivery through 2031, lifts BEL order book by ~40%',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'unspecified', amount: 0, raw_phrase: 'Akash NG missile systems' },
    sv_dependency_score: 4,
    sv_dependency_rationale: 'BEL is the sole licensed Indian producer of Akash radar / launcher / missile systems; deeply embedded with DRDO design.',
    sv_why_this_matters: 'Single largest Akash NG production order. Lifts BEL order book by ~40% to record ₹85,000+ cr. Multi-year delivery cadence locks in defence revenue annuity. Reinforces Atmanirbhar Bharat defence-indigenisation thesis.',
    sv_second_order: {
      beneficiaries: ['Tier-2 defence component vendors', 'Astra Microwave (sub-systems)', 'Paras Defence (optronics)', 'Mishra Dhatu Nigam (alloy supply)'],
      risk: ['Foreign air-defence vendors face market-access friction in India'],
    },
    sv_formatted_line: 'BEL → $2.36B / ₹19,580 cr, Defense / Aerospace, GoI MoD ([2025-09-26] Impact: 6y visibility) 🧭 policy-backed 🔥 backlog reset',
  },

  {
    id: 'seed-hal-tejas-2025-08-28',
    title: 'HAL receives ₹62,370 crore order for 97 Tejas Mk1A LCA aircraft — IAF deliveries through FY2031',
    source_name: 'PIB India',
    source_url: 'https://pib.gov.in/PressReleasePage.aspx?PRID=HAL-Tejas-Mk1A',
    published_at: '2025-08-28T12:00:00Z',
    recorded_at: '2025-08-28T12:00:00Z',
    region: 'IN',
    ticker_symbols: ['HAL'],
    primary_ticker: 'HAL',
    strategic_visibility: {
      qualifies: true,
      theme: 'DEFENSE_AEROSPACE',
      counterparty_tier: 'TIER1_GOV_DEFENSE',
      counterparty_name: 'GoI / IAF',
      contract_value_usd_m: 7510,
      visibility_years: 6,
      flags: ['MCAP_GRADE', 'POLICY_BACKED', 'BACKLOG_RESET'],
      is_chokepoint_override: false,
      is_policy_framework: true,
      reason: '₹62,370 cr ($7.51B) Tejas Mk1A LCA production order — 97 aircraft delivery through FY2031; second tranche after the original 83-aircraft order',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'unspecified', amount: 97, raw_phrase: '97 Tejas Mk1A LCA' },
    sv_dependency_score: 5,
    sv_dependency_rationale: 'HAL is the sole Indian fighter-aircraft producer with active production line; switching cost effectively infinite.',
    sv_why_this_matters: 'Lifts HAL fixed-wing order book to ~₹1.5L cr. Anchors revenue visibility through 2031. Pulls forward downstream aerostructures + electronic warfare suite demand.',
    sv_second_order: {
      beneficiaries: ['BEL — radar + EW', 'Bharat Forge — landing gear / structurals', 'Astra Microwave — sub-systems', 'Paras Defence — optronics'],
      risk: ['Foreign fighter OEMs (Sukhoi / Saab / Boeing) lose Indian share'],
    },
    sv_formatted_line: 'HAL → $7.51B / ₹62,370 cr, Defense / Aerospace, GoI IAF ([2025-08-28] Impact: 6y visibility) 🌟 mcap-grade 🧭 policy-backed 🔥 backlog reset',
  },

  {
    id: 'seed-bdl-astra-2025-07-15',
    title: 'BDL secures ₹2,960 crore Astra Mk1 BVRAAM production order from IAF — multi-year delivery framework',
    source_name: 'PIB India',
    source_url: 'https://pib.gov.in/PressReleasePage.aspx?PRID=BDL-Astra',
    published_at: '2025-07-15T12:00:00Z',
    recorded_at: '2025-07-15T12:00:00Z',
    region: 'IN',
    ticker_symbols: ['BDL'],
    primary_ticker: 'BDL',
    strategic_visibility: {
      qualifies: true,
      theme: 'DEFENSE_AEROSPACE',
      counterparty_tier: 'TIER1_GOV_DEFENSE',
      counterparty_name: 'GoI / IAF',
      contract_value_usd_m: 357,
      visibility_years: 5,
      flags: ['POLICY_BACKED'],
      is_chokepoint_override: false,
      is_policy_framework: true,
      reason: '₹2,960 cr ($357M) Astra Mk1 BVRAAM production order — multi-year delivery framework; lifts BDL missile order book by ~25%',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'unspecified', amount: 0, raw_phrase: 'Astra Mk1 BVRAAM missiles' },
    sv_dependency_score: 4,
    sv_dependency_rationale: 'BDL is the licensed Indian producer of Astra missiles; deeply embedded with DRDO design and IAF qualification cycle.',
    sv_why_this_matters: 'First major commercial Astra production order. Reinforces BDL pivot from foreign-licensed missiles to indigenous Astra/Akash NG production. Validates DRDO indigenous-missile pipeline.',
    sv_second_order: {
      beneficiaries: ['Astra Microwave (RF seekers)', 'Solar Industries (propellants)', 'Premier Explosives (warheads)'],
      risk: ['Foreign BVRAAM vendors face market-access friction'],
    },
    sv_formatted_line: 'BDL → $357M / ₹2,960 cr, Defense / Aerospace, GoI IAF ([2025-07-15] Impact: 5y visibility) 🧭 policy-backed',
  },

  {
    id: 'seed-mazdock-p75i-2025-12-10',
    title: 'Mazagon Dock secures ₹70,000 crore P75-Alpha submarine framework agreement — 6 next-gen conventional submarines through 2035',
    source_name: 'PIB India',
    source_url: 'https://pib.gov.in/PressReleasePage.aspx?PRID=MazDock-P75A',
    published_at: '2025-12-10T12:00:00Z',
    recorded_at: '2025-12-10T12:00:00Z',
    region: 'IN',
    ticker_symbols: ['MAZDOCK'],
    primary_ticker: 'MAZDOCK',
    strategic_visibility: {
      qualifies: true,
      theme: 'DEFENSE_AEROSPACE',
      counterparty_tier: 'TIER1_GOV_DEFENSE',
      counterparty_name: 'GoI / Indian Navy',
      contract_value_usd_m: 8430,
      visibility_years: 10,
      flags: ['MCAP_GRADE', 'DECADE_VISIBILITY', 'POLICY_BACKED'],
      is_chokepoint_override: false,
      is_policy_framework: true,
      reason: '₹70,000 cr ($8.43B) P75-Alpha submarine framework — 6 next-gen conventional submarines with AIP technology through 2035',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'unspecified', amount: 6, raw_phrase: '6 P75-A submarines' },
    sv_dependency_score: 5,
    sv_dependency_rationale: 'Mazagon Dock is the licensed Indian shipyard for conventional submarine construction; infrastructure + IP lock-in absolute.',
    sv_why_this_matters: 'Largest-ever Indian shipyard order. Anchors Mazagon Dock revenue visibility through 2035. Reinforces Indian Navy modernization roadmap and Atmanirbhar Bharat naval-indigenisation.',
    sv_second_order: {
      beneficiaries: ['L&T — pressure-hull steel + sub-system integration', 'BEL — combat management system', 'BDL — torpedoes', 'Premier Explosives — warheads'],
      risk: ['Foreign submarine OEMs (TKMS / Naval Group / Navantia) face Indian-market lockout'],
    },
    sv_formatted_line: 'MAZDOCK → $8.43B / ₹70,000 cr, Defense / Aerospace, GoI Navy ([2025-12-10] Impact: 10y visibility) 🌟 mcap-grade ✅ 10y visibility 🧭 policy-backed',
  },

  {
    id: 'seed-pgcil-tbcb-2025-11-28',
    title: 'Power Grid Corp wins ₹15,420 crore HVDC + transmission TBCB tariff-based bidding awards — 25-year ToCC framework',
    source_name: 'BSE Corp Announcements',
    source_url: 'https://www.bseindia.com/corporates/ann.html?company=PGCIL',
    published_at: '2025-11-28T12:00:00Z',
    recorded_at: '2025-11-28T12:00:00Z',
    region: 'IN',
    ticker_symbols: ['POWERGRID'],
    primary_ticker: 'POWERGRID',
    strategic_visibility: {
      qualifies: true,
      theme: 'POWER_GRID',
      counterparty_tier: 'TOP3_UTILITY',
      counterparty_name: 'CTUIL / GoI',
      contract_value_usd_m: 1860,
      visibility_years: 25,
      flags: ['DECADE_VISIBILITY', 'BACKLOG_RESET'],
      is_chokepoint_override: false,
      is_policy_framework: false,
      reason: '₹15,420 cr ($1.86B) HVDC + transmission TBCB awards — 25-year transmission-of-capacity-charge framework; lifts PGCIL annuity revenue base materially',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'tcap_GW', amount: 8, raw_phrase: '~8GW HVDC + transmission capacity' },
    sv_dependency_score: 4,
    sv_dependency_rationale: 'TBCB awards are 25-year regulated annuities; once won, revenue is locked.',
    sv_why_this_matters: 'Reinforces PGCIL pivot from regulated-PSU to TBCB-led growth. 25-year visibility creates infrastructure-grade earnings base. Pulls forward transformer / switchgear / cable demand.',
    sv_second_order: {
      beneficiaries: ['Transformers India / CG Power / Hitachi Energy — transformers', 'KEC / Sterlite Power — transmission EPC', 'Polycab / Apar — cables'],
      risk: ['Adani Energy Solutions / Tata Power Trans — direct TBCB competition'],
    },
    sv_formatted_line: 'POWERGRID → $1.86B / ₹15,420 cr, 8GW, Power / Grid, CTUIL ([2025-11-28] Impact: 25y visibility) ✅ 10y visibility 🔥 backlog reset',
  },

  {
    id: 'seed-bhel-fgd-2025-10-15',
    title: 'BHEL secures ₹11,800 crore Flue Gas Desulphurization framework — NTPC + state-utility 600MW+ thermal retrofit through 2030',
    source_name: 'BSE Corp Announcements',
    source_url: 'https://www.bseindia.com/corporates/ann.html?company=BHEL',
    published_at: '2025-10-15T12:00:00Z',
    recorded_at: '2025-10-15T12:00:00Z',
    region: 'IN',
    ticker_symbols: ['BHEL'],
    primary_ticker: 'BHEL',
    strategic_visibility: {
      qualifies: true,
      theme: 'ENERGY_TRANSITION',
      counterparty_tier: 'TOP3_UTILITY',
      counterparty_name: 'NTPC + State Utilities',
      contract_value_usd_m: 1420,
      visibility_years: 5,
      flags: ['POLICY_BACKED'],
      is_chokepoint_override: false,
      is_policy_framework: true,
      reason: '₹11,800 cr ($1.42B) FGD framework from NTPC + state utilities — multi-year retrofit through 2030 driven by SOx emission norms',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'unspecified', amount: 0, raw_phrase: 'FGD systems for 600MW+ thermal units' },
    sv_dependency_score: 3,
    sv_dependency_rationale: 'BHEL has the largest FGD portfolio in India; license + EPC capacity advantage vs L&T / Doosan.',
    sv_why_this_matters: 'Largest single FGD framework. Validates BHEL pivot from declining new-thermal to retrofit + emissions-control. Multi-year cadence stabilizes earnings.',
    sv_second_order: {
      beneficiaries: ['Limestone / specialty-chemical vendors', 'Industrial automation OEMs (Siemens India / ABB)'],
      risk: ['L&T / Thermax — competing FGD share'],
    },
    sv_formatted_line: 'BHEL → $1.42B / ₹11,800 cr, Energy Transition, NTPC + State ([2025-10-15] Impact: 5y visibility) 🧭 policy-backed',
  },

  {
    id: 'seed-rvnl-vande-2025-08-12',
    title: 'RVNL wins ₹26,000 crore Vande Bharat sleeper trainset framework — 200 trainsets + 35-year maintenance through 2060',
    source_name: 'BSE Corp Announcements',
    source_url: 'https://www.bseindia.com/corporates/ann.html?company=RVNL',
    published_at: '2025-08-12T12:00:00Z',
    recorded_at: '2025-08-12T12:00:00Z',
    region: 'IN',
    ticker_symbols: ['RVNL'],
    primary_ticker: 'RVNL',
    strategic_visibility: {
      qualifies: true,
      theme: 'CRITICAL_NATIONAL_PROGRAM',
      counterparty_tier: 'TIER1_GOV_DEFENSE',
      counterparty_name: 'Indian Railways',
      contract_value_usd_m: 3130,
      visibility_years: 35,
      flags: ['MCAP_GRADE', 'DECADE_VISIBILITY', 'POLICY_BACKED'],
      is_chokepoint_override: false,
      is_policy_framework: true,
      reason: '₹26,000 cr ($3.13B) Vande Bharat sleeper trainset framework — 200 trainsets + 35-year maintenance contract through 2060',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'unspecified', amount: 200, raw_phrase: '200 Vande Bharat sleeper trainsets' },
    sv_dependency_score: 4,
    sv_dependency_rationale: 'Long-tenor maintenance lock; 35-year recurring annuity unmatched in Indian rail.',
    sv_why_this_matters: 'Largest single Indian Railways order with ultra-long-tenor maintenance annuity. Re-rates RVNL from project EPC to infrastructure operator. Pulls forward rolling-stock + signaling demand.',
    sv_second_order: {
      beneficiaries: ['BHEL / Titagarh — rolling stock partners', 'KEC / Larsen — electrification', 'Honeywell / Bombardier — signaling'],
      risk: ['Foreign rail OEMs face long-tenor lockout from Indian high-speed segment'],
    },
    sv_formatted_line: 'RVNL → $3.13B / ₹26,000 cr, 200 trainsets, Critical National Program, Indian Railways ([2025-08-12] Impact: 35y visibility) 🌟 mcap-grade ✅ 10y visibility 🧭 policy-backed',
  },

  {
    id: 'seed-ntpc-seci-ppa-2025-06-30',
    title: 'NTPC PPA framework signs 25-year solar/wind PPAs covering ~5GW under SECI Tranche XII — multi-developer 25-year offtake',
    source_name: 'NTPC Press',
    source_url: 'https://www.ntpc.co.in/en/media-center/press-release',
    published_at: '2025-06-30T12:00:00Z',
    recorded_at: '2025-06-30T12:00:00Z',
    region: 'IN',
    ticker_symbols: ['NTPC'],
    primary_ticker: 'NTPC',
    strategic_visibility: {
      qualifies: true,
      theme: 'ENERGY_TRANSITION',
      counterparty_tier: 'TOP3_UTILITY',
      counterparty_name: 'SECI / GoI',
      contract_value_usd_m: 4820,
      visibility_years: 25,
      flags: ['DECADE_VISIBILITY', 'POLICY_BACKED'],
      is_chokepoint_override: false,
      is_policy_framework: true,
      reason: '~5GW solar/wind PPA framework with 25-year offtake — anchors NTPC Renewable energy roadmap, ~₹40,000 cr ($4.82B) implied capex',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'GW', amount: 5, raw_phrase: '~5GW solar/wind PPA' },
    sv_dependency_score: 3,
    sv_dependency_rationale: 'PPA-anchored renewable capacity with 25-year offtake creates infrastructure-grade revenue base.',
    sv_why_this_matters: 'Anchors NTPC pivot from coal-PSU to integrated energy company. 25-year offtake stabilizes earnings. Pulls forward solar PV / wind / BESS / transmission demand.',
    sv_second_order: {
      beneficiaries: ['Waaree / Premier Energies — solar modules', 'Inox Wind / Suzlon — wind turbines', 'KP Energy / KPI Green — solar EPC', 'Bondada / Sterling & Wilson — EPC'],
      risk: ['Coal-only thermal IPPs face stranded-asset risk'],
    },
    sv_formatted_line: 'NTPC → $4.82B, 5GW, Energy Transition, SECI ([2025-06-30] Impact: 25y visibility) ✅ 10y visibility 🧭 policy-backed',
  },

  // ─── SEMI SUPPLY CHAIN MEGA-FAB ────────────────────────────────────────
  {
    id: 'seed-tsmc-az-expand-2025-03-03',
    title: 'TSMC expands Arizona fab investment to $165B — third fab + advanced packaging + R&D center, supports US semiconductor sovereignty',
    source_name: 'Reuters',
    source_url: 'https://www.reuters.com/technology/tsmc-arizona-165b-expansion/',
    published_at: '2025-03-03T12:00:00Z',
    recorded_at: '2025-03-03T12:00:00Z',
    region: 'US',
    ticker_symbols: ['TSM'],
    primary_ticker: 'TSM',
    strategic_visibility: {
      qualifies: true,
      theme: 'SEMI_SUPPLY_CHAIN',
      counterparty_tier: 'TIER1_GOV_DEFENSE',
      counterparty_name: 'US Government / DOC',
      contract_value_usd_m: 165000,
      visibility_years: 10,
      flags: ['MCAP_GRADE', 'DECADE_VISIBILITY', 'POLICY_BACKED'],
      is_chokepoint_override: false,
      is_policy_framework: true,
      reason: '$165B Arizona fab framework — third fab + advanced packaging + R&D; CHIPS Act anchor program; multi-decade US semiconductor onshoring',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'fab_pct', amount: 3, raw_phrase: '3 fabs + advanced packaging + R&D' },
    sv_dependency_score: 5,
    sv_dependency_rationale: 'TSMC is the chokepoint for leading-edge logic; US fab expansion is sovereign-program-grade.',
    sv_why_this_matters: 'Largest-ever foreign direct investment in US semis. Anchors CHIPS Act and US sovereignty roadmap. Pulls forward equipment / construction / power / chemicals demand for a decade.',
    sv_second_order: {
      beneficiaries: ['Applied Materials / LRCX / KLAC — equipment', 'ASML — EUV', 'JSR / Tokyo Ohka — photoresist', 'AMAT / Linde — gases', 'Quanta / Bechtel — fab construction'],
      risk: ['Mature-node foundries face share loss', 'Asian-only fab supply chain faces geopolitical re-routing'],
    },
    sv_formatted_line: 'TSM → $165B, 3 fabs, Semi Supply Chain, US Gov ([2025-03-03] Impact: 10y visibility) 🌟 mcap-grade ✅ 10y visibility 🧭 policy-backed',
  },

  {
    id: 'seed-mu-ny-fab-2024-12-10',
    title: 'Micron secures $6.1B CHIPS Act + $7.5B EXIM financing for $50B+ NY/ID fab framework — 10-year US memory expansion',
    source_name: 'Reuters',
    source_url: 'https://www.reuters.com/technology/micron-ny-id-fab-framework/',
    published_at: '2024-12-10T12:00:00Z',
    recorded_at: '2024-12-10T12:00:00Z',
    region: 'US',
    ticker_symbols: ['MU'],
    primary_ticker: 'MU',
    strategic_visibility: {
      qualifies: true,
      theme: 'SEMI_SUPPLY_CHAIN',
      counterparty_tier: 'TIER1_GOV_DEFENSE',
      counterparty_name: 'US DOC / EXIM',
      contract_value_usd_m: 50000,
      visibility_years: 10,
      flags: ['MCAP_GRADE', 'DECADE_VISIBILITY', 'POLICY_BACKED'],
      is_chokepoint_override: false,
      is_policy_framework: true,
      reason: '$50B+ NY/ID fab framework with $6.1B CHIPS Act + $7.5B EXIM financing — 10-year US memory onshoring program',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'fab_pct', amount: 4, raw_phrase: '4-fab US memory campus' },
    sv_dependency_score: 4,
    sv_dependency_rationale: 'Micron is the only US-headquartered DRAM/NAND producer at scale; US sovereignty alignment.',
    sv_why_this_matters: 'Largest US DRAM expansion in two decades. Anchors HBM/DRAM US-onshoring. Pulls forward equipment / power / construction demand.',
    sv_second_order: {
      beneficiaries: ['Applied Materials / LRCX / KLAC — equipment', 'JSR / Tokyo Ohka — photoresist', 'Linde / AirProducts — gases'],
      risk: ['Asian-only DRAM supply faces share rebalancing', 'Construction labor demand spikes regionally'],
    },
    sv_formatted_line: 'MU → $50B+, 4 fabs, Semi Supply Chain, US DOC/EXIM ([2024-12-10] Impact: 10y visibility) 🌟 mcap-grade ✅ 10y visibility 🧭 policy-backed',
  },

  // ─── NUCLEAR / SMR / URANIUM CHOKEPOINTS ───────────────────────────────
  {
    id: 'seed-bwxt-naval-2025-03-25',
    title: 'BWX Technologies awarded $2.6B US Navy multi-year naval reactor manufacturing contract — Columbia/Virginia class through 2034',
    source_name: 'Defense News',
    source_url: 'https://www.defensenews.com/naval/bwxt-navy-reactor-contract/',
    published_at: '2025-03-25T12:00:00Z',
    recorded_at: '2025-03-25T12:00:00Z',
    region: 'US',
    ticker_symbols: ['BWXT'],
    primary_ticker: 'BWXT',
    strategic_visibility: {
      qualifies: true,
      theme: 'DEFENSE_AEROSPACE',
      counterparty_tier: 'TIER1_GOV_DEFENSE',
      counterparty_name: 'US Navy',
      contract_value_usd_m: 2600,
      visibility_years: 9,
      flags: ['STRATEGIC_CHOKEPOINT', 'POLICY_BACKED', 'DECADE_VISIBILITY'],
      is_chokepoint_override: true,
      is_policy_framework: true,
      reason: '$2.6B US Navy naval reactor manufacturing contract through 2034 — sole producer of Naval reactors for Columbia/Virginia class submarines',
    },
    sv_signal_quality_tier: 'A_FILING',
    sv_capacity_reserved: { unit: 'unspecified', amount: 0, raw_phrase: 'Naval reactor cores Columbia/Virginia class' },
    sv_dependency_score: 5,
    sv_dependency_rationale: 'BWXT is the sole US producer of Naval reactor cores; chokepoint for SSBN/SSN replacement program.',
    sv_why_this_matters: 'Sole-source Naval reactor framework reinforces SSBN/SSN replacement program through 2034. State-backed demand visibility for nuclear-naval propulsion. Reinforces commercial SMR optionality.',
    sv_second_order: {
      beneficiaries: ['Specialty steel / nickel-alloy forge specialists (Carpenter Tech / ATI)', 'HALEU enrichment (Centrus)', 'SMR developers (X-energy / TerraPower) — leverage Naval reactor IP'],
      risk: ['Foreign nuclear-naval competitors (Rosatom) face market lockout'],
    },
    sv_formatted_line: 'BWXT → $2.6B, Defense / Aerospace, US Navy ([2025-03-25] Impact: 9y visibility) 🔒 chokepoint 🧭 policy-backed ✅ 10y visibility',
  },

  {
    id: 'seed-ccj-westinghouse-2025-04-18',
    title: 'Cameco / Brookfield Westinghouse secures $14.5B+ multi-decade nuclear fuel + reactor service framework — Western nuclear sovereignty',
    source_name: 'World Nuclear News',
    source_url: 'https://world-nuclear-news.org/articles/cameco-westinghouse-framework',
    published_at: '2025-04-18T12:00:00Z',
    recorded_at: '2025-04-18T12:00:00Z',
    region: 'US',
    ticker_symbols: ['CCJ'],
    primary_ticker: 'CCJ',
    strategic_visibility: {
      qualifies: true,
      theme: 'CRITICAL_NATIONAL_PROGRAM',
      counterparty_tier: 'TIER1_GOV_DEFENSE',
      counterparty_name: 'DOE / Western utilities',
      contract_value_usd_m: 14500,
      visibility_years: 20,
      flags: ['MCAP_GRADE', 'DECADE_VISIBILITY', 'POLICY_BACKED', 'STRATEGIC_CHOKEPOINT'],
      is_chokepoint_override: true,
      is_policy_framework: true,
      reason: 'Westinghouse nuclear fuel + reactor service framework — multi-decade Western nuclear sovereignty pillar; CCJ owns 49% upstream uranium-enrichment-fuel chain',
    },
    sv_signal_quality_tier: 'B_TIER1_MEDIA',
    sv_capacity_reserved: { unit: 'unspecified', amount: 0, raw_phrase: 'Multi-decade Western nuclear fuel + AP1000/AP300 service' },
    sv_dependency_score: 5,
    sv_dependency_rationale: 'CCJ owns largest Western uranium reserves + 49% Westinghouse — full-stack chokepoint vs Russian TENEX.',
    sv_why_this_matters: 'Anchors Western nuclear sovereignty. Multi-decade fuel-cycle annuity. Pulls forward uranium mining, conversion, enrichment, and reactor-service demand. Re-rates CCJ from cyclical miner to integrated nuclear utility.',
    sv_second_order: {
      beneficiaries: ['Uranium miners (DNN / NXE / UEC)', 'HALEU enrichment (LEU)', 'SMR developers (X-energy / NuScale)', 'Reactor-component vendors'],
      risk: ['Russian TENEX-dependent reactors face fuel substitution'],
    },
    sv_formatted_line: 'CCJ → $14.5B+, Critical National Program, DOE / Western utilities ([2025-04-18] Impact: 20y visibility) 🌟 mcap-grade ✅ 10y visibility 🧭 policy-backed 🔒 chokepoint',
  },

  // ─── HBM MEMORY / ADVANCED PACKAGING CHOKEPOINTS ───────────────────────
  {
    id: 'seed-skh-hbm-2024-09-16',
    title: 'SK hynix locks in $40B+ HBM3E/HBM4 multi-year customer commitments — NVIDIA/AMD/Broadcom multi-year offtake through 2027',
    source_name: 'TrendForce',
    source_url: 'https://www.trendforce.com/news/sk-hynix-hbm-mega-offtake/',
    published_at: '2024-09-16T12:00:00Z',
    recorded_at: '2024-09-16T12:00:00Z',
    region: 'US',
    ticker_symbols: ['HXSCL'],
    primary_ticker: 'HXSCL',
    strategic_visibility: {
      qualifies: true,
      theme: 'SEMI_SUPPLY_CHAIN',
      counterparty_tier: 'HYPERSCALER',
      counterparty_name: 'NVIDIA / AMD / Broadcom',
      contract_value_usd_m: 40000,
      visibility_years: 3,
      flags: ['MCAP_GRADE', 'BACKLOG_RESET', 'STRATEGIC_CHOKEPOINT'],
      is_chokepoint_override: true,
      is_policy_framework: false,
      reason: '$40B+ HBM3E/HBM4 multi-year customer commitments — chokepoint memory supplier with sub-3 global competitors (Samsung / Micron lag)',
    },
    sv_signal_quality_tier: 'C_INDUSTRY',
    sv_capacity_reserved: { unit: 'HBM_kpcs_pm', amount: 250, raw_phrase: '~250kpcs/mo HBM allocation reserved' },
    sv_dependency_score: 5,
    sv_dependency_rationale: 'HBM3E is sub-3 global supplier (SKH / Samsung / Micron). SKH leads in HBM3E qualification — switching cost very high.',
    sv_why_this_matters: 'Largest disclosed HBM allocation framework. HBM is the binding bottleneck for GPU AI training; locks pricing power for SKH through 2027. Pulls forward CoWoS / advanced-packaging demand.',
    sv_second_order: {
      beneficiaries: ['Specialty gas / photoresist (JSR / Tokyo Ohka)', 'Advanced packaging (TSMC / ASE)', 'DRAM equipment makers'],
      risk: ['Non-reserved GPU buyers face HBM allocation queue', 'Samsung / Micron face share-of-wallet pressure'],
    },
    sv_formatted_line: 'HXSCL → $40B+, 250kpcs/mo HBM, Semi Supply Chain, NVIDIA/AMD/Broadcom ([2024-09-16] Impact: 3y visibility) 🌟 mcap-grade 🔥 backlog reset 🔒 chokepoint',
  },
];

// ─── seedTransformational — merge into KV ledger ──────────────────────────
//
// Called once per news-fetch cycle. Idempotent — recordTransformational
// de-dupes by id, so re-running is safe.

import { recordTransformational } from './transformational-ledger';

export async function seedTransformational(): Promise<{ written: number }> {
  let written = 0;
  for (const item of TRANSFORMATIONAL_SEED) {
    try {
      await recordTransformational(item);
      written++;
    } catch (e) {
      // Best-effort — never fail the news loop on seed write
    }
  }
  return { written };
}
